### ISSUE TITLE
Could not build against zlib

### ISSUE THREAD

**Issue by RedJayGames** [TomerAberbach/tcnj-vpn#1]
This could potentially be because of my machine; I'm very new to using Linux.

When running ./configure, it produces an error. Below is the error and the lines of output that I believe may help in diagnosing the issue:

checking for ZLIB... no
checking for zlib without pkg-config... no
configure: error: Could not build against zlib

For reference, I am running on Ubuntu 19.10

**Comment by TomerAberbach** [comment]
Hi! Thanks for reporting the issue.

The reason it didn't work is because I hadn't updated the project to work for newer versions of Ubuntu. But now I've updated it! So try the install script again and let me know if it works.

**Comment by RedJayGames** [comment]
It worked! Thank you.

As a side note, I was unable to use the install script because it said I already had the vpn installed, but it could not find the uninstall script when I tried to run it, despite having downloaded the entire project in a zip file and extracting all of it. Using curl also did not work. I was able to work around this and successfully install and connect to the vpn using the tutorial, however.

Again, thank you very much!

**Comment by TomerAberbach** [comment]
No problem!

Yeah, I realize now that the uninstall script wouldn't work for you. I updated the uninstall logic as well (to match the new install script) so it didn't work because you had installed with the old install script. I would have said to remove the openconnect folder which was created by the old install script, but it looks like you figured that out.

Hope all goes smoothly now. Feel free to open another issue if you experience any problems in the future. Stay safe!
